define({
    "root": {
        "lblOpen_key": "Open",
        "lblHigh_key": "High",
        "lblLow_key": "Low",
        "lblClose_key": "Close",
        "lblVolume_key": "Volume",
        "lblUpVol_key": "Up Vol",
        "lblDownVol_key": "Down Vol",
        "lblOpen_Interest_key": "OpenInt.",
        "lblOpen_short_key": "O",
        "lblHigh_short_key": "Hi",
        "lblLow_short_key": "Lo",
        "lblLast_short_key" : "L",
        "lblExchange_short_key": "",
        "lblDescription_short_key": "",
        "lblNetChange_short_key": "",
        "lblNetChangePct_short_key": "",
        "lblBid_short_key": "B",
        "lblAsk_short_key": "A",
        "lblVolume_short_key": "V",
        "lblDailyOpenInterest_short_key": "OI",
        "lblam_short_key": "am",
        "lblpm_short_key": "pm",
        "lblAM_short_key": "AM",
        "lblPM_short_key": "PM",
        "lblMonths_short_key": ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        "lblMonths_key": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "lblDays_short_key": ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        "lblDays_key": ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        "lblLoading_key" : "Loading",
        "lblError_key" : "Oops! We have encountered an error returning the charting data."
    },
    "ja-jp": false
});